name: small_application
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^3.2.0
  equatable: ^1.1.1
  floor: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  sqflite_ffi_test:
    git:
      url: git://github.com/tekartik/sqflite_more
      ref: dart2
      path: sqflite_ffi_test

  floor_generator: ^0.11.0
  build_runner: ^1.7.3


flutter:

  uses-material-design: true

  assets:
    - assets/data.json

  fonts:
    - family: Oswald
      fonts:
        - asset: fonts/Oswald-Regular.ttf
